package com.softdesign.devintensive.data.storage.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.softdesign.devintensive.data.storage.model.Repository;
import com.softdesign.devintensive.data.storage.model.User;

import com.softdesign.devintensive.data.storage.model.RepositoryDao;
import com.softdesign.devintensive.data.storage.model.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig repositoryDaoConfig;
    private final DaoConfig userDaoConfig;

    private final RepositoryDao repositoryDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        repositoryDaoConfig = daoConfigMap.get(RepositoryDao.class).clone();
        repositoryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        repositoryDao = new RepositoryDao(repositoryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Repository.class, repositoryDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        repositoryDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public RepositoryDao getRepositoryDao() {
        return repositoryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
